name: HACS Validation

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          
      - name: Validate hacs.json
        run: |
          python -c "
          import json
          hacs_config = json.load(open('hacs.json'))
          required_keys = ['name', 'domains', 'iot_class', 'homeassistant']
          for key in required_keys:
              assert key in hacs_config, f'Missing {key} in hacs.json'
          print('✅ HACS configuration valid')
          "
