create_dashboard:
  description: Erstellt ein Dashboard für den Hund
  fields:
    dog_name:
      name: Hundename
      required: true

setup_helpers:
  description: Erstellt alle benötigten Helfer für den Hund
  fields:
    dog_name:
      name: Hundename
      required: true

log_activity:
  description: Protokolliert eine Aktivität (walk, feeding, potty)
  fields:
    dog_name:
      name: Hundename
      required: true
    activity_type:
      name: Aktivitätstyp
      example: walk

send_notification:
  description: Sendet eine Push-Nachricht an anwesende Personen
  fields:
    dog_name:
      name: Hundename
      required: true
    message:
      name: Nachricht
      required: true


generate_stat_sensors:
  description: Erstellt Statistik-Sensoren (utility_meter) für einen Hund
  fields:
    dog_name:
      name: Hundename
      required: true


generate_automations:
  description: Erstellt Automatisierungen für einen Hund
  fields:
    dog_name:
      name: Hundename
      required: true
    notify_target:
      name: Ziel für Push (z. B. mobile_app_xyz)
      required: true
