feed_dog:
  name: Hund füttern
  description: Markiert eine Mahlzeit als gegeben und aktualisiert die Fütterungsstatistiken.
  target: {}
  fields:
    meal_type:
      name: Mahlzeit-Typ
      description: Art der Mahlzeit
      required: false
      default: ""
      selector:
        select:
          options:
            - label: "Frühstück"
              value: "morning"
            - label: "Mittagessen"
              value: "lunch"
            - label: "Abendessen"
              value: "evening"
            - label: "Leckerli"
              value: "snack"
    portion_size:
      name: Portionsgröße
      description: Größe der Portion
      required: false
      default: "normal"
      selector:
        select:
          options:
            - label: "Klein"
              value: "small"
            - label: "Normal"
              value: "normal"
            - label: "Groß"
              value: "large"
    notes:
      name: Notizen
      description: Zusätzliche Notizen zur Fütterung
      required: false
      selector:
        text:
          multiline: true

walk_dog:
  name: Gassi gehen
  description: Zeichnet einen Spaziergang auf und aktualisiert die Aktivitätsstatistiken.
  target: {}
  fields:
    duration:
      name: Dauer
      description: Dauer des Spaziergangs in Minuten
      required: false
      default: 30
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: "min"
    distance:
      name: Distanz
      description: Zurückgelegte Distanz in Kilometern
      required: false
      selector:
        text:
          type: "text"
    notes:
      name: Notizen
      description: Notizen zum Spaziergang
      required: false
      selector:
        text:
          multiline: true
    weather:
      name: Wetter
      description: Wetterbedingungen während des Spaziergangs
      required: false
      selector:
        select:
          options:
            - label: "Sonnig"
              value: "sunny"
            - label: "Bewölkt"
              value: "cloudy"
            - label: "Regen"
              value: "rainy"
            - label: "Schnee"
              value: "snowy"
            - label: "Windig"
              value: "windy"

play_with_dog:
  name: Mit Hund spielen
  description: Zeichnet eine Spielsession auf und aktualisiert die Aktivitätsstatistiken.
  target: {}
  fields:
    duration:
      name: Dauer
      description: Dauer der Spielsession in Minuten
      required: false
      default: 15
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: "min"
    play_type:
      name: Spiel-Art
      description: Art des Spiels
      required: false
      default: "general"
      selector:
        select:
          options:
            - label: "Allgemein"
              value: "general"
            - label: "Apportieren"
              value: "fetch"
            - label: "Tauziehen"
              value: "tug"
            - label: "Freies Spiel"
              value: "free_play"
            - label: "Verstecken"
              value: "hide_seek"
            - label: "Agility"
              value: "agility"
    intensity:
      name: Intensität
      description: Intensität des Spiels
      required: false
      default: "medium"
      selector:
        select:
          options:
            - label: "Niedrig"
              value: "low"
            - label: "Mittel"
              value: "medium"
            - label: "Hoch"
              value: "high"
    notes:
      name: Notizen
      description: Notizen zur Spielsession
      required: false
      selector:
        text:
          multiline: true

training_session:
  name: Training
  description: Zeichnet eine Trainingsession auf.
  target: {}
  fields:
    duration:
      name: Dauer
      description: Dauer des Trainings in Minuten
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "min"
    training_type:
      name: Training-Art
      description: Art des Trainings
      required: false
      default: "basic"
      selector:
        select:
          options:
            - label: "Grundkommandos"
              value: "basic"
            - label: "Fortgeschrittene Kommandos"
              value: "advanced"
            - label: "Tricks"
              value: "tricks"
            - label: "Sozialverhalten"
              value: "social"
            - label: "Leinenführigkeit"
              value: "leash"
            - label: "Rückruf"
              value: "recall"
    commands:
      name: Kommandos
      description: Geübte Kommandos
      required: false
      selector:
        text:
          multiline: true
    success_rate:
      name: Erfolgsrate
      description: Erfolgsrate des Trainings
      required: false
      default: "good"
      selector:
        select:
          options:
            - label: "Schlecht"
              value: "poor"
            - label: "Gut"
              value: "good"
            - label: "Ausgezeichnet"
              value: "excellent"
    notes:
      name: Notizen
      description: Notizen zum Training
      required: false
      selector:
        text:
          multiline: true

health_check:
  name: Gesundheitscheck
  description: Führt einen Gesundheitscheck durch und aktualisiert die Gesundheitsdaten.
  target: {}
  fields:
    health_status:
      name: Gesundheitsstatus
      description: Aktueller Gesundheitsstatus
      required: false
      selector:
        select:
          options:
            - label: "Ausgezeichnet"
              value: "Ausgezeichnet"
            - label: "Gut"
              value: "Gut"
            - label: "Normal"
              value: "Normal"
            - label: "Schwach"
              value: "Schwach"
            - label: "Krank"
              value: "Krank"
            - label: "Notfall"
              value: "Notfall"
    weight:
      name: Gewicht
      description: Aktuelles Gewicht in kg
      required: false
      selector:
        number:
          min: 0.5
          max: 100
          step: 0.1
          unit_of_measurement: "kg"
    temperature:
      name: Temperatur
      description: Körpertemperatur in °C
      required: false
      selector:
        number:
          min: 35.0
          max: 42.0
          step: 0.1
          unit_of_measurement: "°C"
    mood:
      name: Stimmung
      description: Aktuelle Stimmung
      required: false
      selector:
        select:
          options:
            - label: "Sehr glücklich"
              value: "Sehr glücklich"
            - label: "Glücklich"
              value: "Glücklich"
            - label: "Neutral"
              value: "Neutral"
            - label: "Gestresst"
              value: "Gestresst"
            - label: "Ängstlich"
              value: "Ängstlich"
            - label: "Krank"
              value: "Krank"
    appetite:
      name: Appetit
      description: Aktueller Appetit
      required: false
      selector:
        select:
          options:
            - label: "Kein Appetit"
              value: "Kein Appetit"
            - label: "Wenig Appetit"
              value: "Wenig Appetit"
            - label: "Normal"
              value: "Normal"
            - label: "Guter Appetit"
              value: "Guter Appetit"
            - label: "Sehr hungrig"
              value: "Sehr hungrig"
    energy_level:
      name: Energie Level
      description: Aktuelles Energie Level
      required: false
      selector:
        select:
          options:
            - label: "Sehr müde"
              value: "Sehr müde"
            - label: "Müde"
              value: "Müde"
            - label: "Normal"
              value: "Normal"
            - label: "Energiegeladen"
              value: "Energiegeladen"
            - label: "Hyperaktiv"
              value: "Hyperaktiv"
    notes:
      name: Notizen
      description: Gesundheitsnotizen
      required: false
      selector:
        text:
          multiline: true

medication_given:
  name: Medikament gegeben
  description: Markiert ein Medikament als gegeben.
  target: {}
  fields:
    medication:
      name: Medikament
      description: Name des Medikaments
      required: false
      selector:
        text:
          type: "text"
    dosage:
      name: Dosierung
      description: Dosierung des Medikaments
      required: false
      selector:
        text:
          type: "text"
    time:
      name: Zeit
      description: Zeit der Medikamentengabe
      required: false
      selector:
        time: {}
    notes:
      name: Notizen
      description: Notizen zur Medikamentengabe
      required: false
      selector:
        text:
          multiline: true

vet_visit:
  name: Tierarztbesuch
  description: Zeichnet einen Tierarztbesuch auf.
  target: {}
  fields:
    visit_type:
      name: Besuchstyp
      description: Art des Tierarztbesuchs
      required: false
      default: "routine"
      selector:
        select:
          options:
            - label: "Routine-Untersuchung"
              value: "routine"
            - label: "Impfung"
              value: "vaccination"
            - label: "Notfall"
              value: "emergency"
            - label: "Nachuntersuchung"
              value: "followup"
            - label: "Operation"
              value: "surgery"
            - label: "Zahnreinigung"
              value: "dental"
    diagnosis:
      name: Diagnose
      description: Diagnose des Tierarztes
      required: false
      selector:
        text:
          multiline: true
    treatment:
      name: Behandlung
      description: Durchgeführte Behandlung
      required: false
      selector:
        text:
          multiline: true
    next_appointment:
      name: Nächster Termin
      description: Datum des nächsten Termins
      required: false
      selector:
        datetime: {}
    cost:
      name: Kosten
      description: Kosten des Besuchs
      required: false
      selector:
        text:
          type: "text"
    notes:
      name: Notizen
      description: Zusätzliche Notizen
      required: false
      selector:
        text:
          multiline: true

grooming_session:
  name: Pflegesession
  description: Zeichnet eine Pflegesession auf.
  target: {}
  fields:
    grooming_type:
      name: Pflege-Art
      description: Art der Pflege
      required: false
      default: "basic"
      selector:
        select:
          options:
            - label: "Grundpflege"
              value: "basic"
            - label: "Vollpflege"
              value: "full"
            - label: "Baden"
              value: "bath"
            - label: "Bürsten"
              value: "brush"
            - label: "Krallen schneiden"
              value: "nails"
            - label: "Ohren reinigen"
              value: "ears"
            - label: "Zähne putzen"
              value: "teeth"
    duration:
      name: Dauer
      description: Dauer der Pflegesession in Minuten
      required: false
      default: 30
      selector:
        number:
          min: 5
          max: 180
          unit_of_measurement: "min"
    professional:
      name: Professionell
      description: Wurde die Pflege professionell durchgeführt
      required: false
      default: false
      selector:
        boolean: {}
    notes:
      name: Notizen
      description: Notizen zur Pflegesession
      required: false
      selector:
        text:
          multiline: true

activate_emergency_mode:
  name: Notfallmodus aktivieren
  description: Aktiviert oder deaktiviert den Notfallmodus für den Hund.
  target: {}
  fields:
    activate:
      name: Aktivieren
      description: Notfallmodus aktivieren oder deaktivieren
      required: false
      default: true
      selector:
        boolean: {}
    reason:
      name: Grund
      description: Grund für den Notfall
      required: false
      selector:
        text:
          multiline: true
    contact_vet:
      name: Tierarzt kontaktieren
      description: Soll der Tierarzt automatisch kontaktiert werden
      required: false
      default: false
      selector:
        boolean: {}

toggle_visitor_mode:
  name: Besuchsmodus umschalten
  description: Aktiviert oder deaktiviert den Besuchsmodus.
  target: {}
  fields:
    activate:
      name: Aktivieren
      description: Besuchsmodus aktivieren oder deaktivieren
      required: false
      selector:
        boolean: {}
    visitor_name:
      name: Besuchername
      description: Name des Besuchers
      required: false
      selector:
        text:
          type: "text"
    start_time:
      name: Startzeit
      description: Startzeit des Besuchs
      required: false
      selector:
        datetime: {}
    end_time:
      name: Endzeit
      description: Endzeit des Besuchs
      required: false
      selector:
        datetime: {}

daily_reset:
  name: Tagesreset
  description: Setzt alle täglichen Werte zurück.
  target: {}
  fields:
    date:
      name: Datum
      description: Datum für den Reset (Standard: heute)
      required: false
      selector:
        date: {}

generate_report:
  name: Bericht generieren
  description: Generiert einen umfassenden Bericht über den Hund.
  target: {}
  fields:
    report_type:
      name: Berichtstyp
      description: Art des Berichts
      required: false
      default: "daily"
      selector:
        select:
          options:
            - label: "Tagesbericht"
              value: "daily"
            - label: "Wochenbericht"
              value: "weekly"
            - label: "Monatsbericht"
              value: "monthly"
            - label: "Jahresbericht"
              value: "yearly"
    include_charts:
      name: Diagramme einschließen
      description: Sollen Diagramme im Bericht enthalten sein
      required: false
      default: false
      selector:
        boolean: {}
    email_report:
      name: Bericht per E-Mail
      description: Soll der Bericht per E-Mail versandt werden
      required: false
      default: false
      selector:
        boolean: {}
