trigger_feeding_reminder:
  name: Fütterungserinnerung senden
  description: Sendet eine Benachrichtigung zur Fütterungserinnerung für einen oder alle Hunde
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    meal_type:
      name: Mahlzeit
      description: Art der Mahlzeit
      required: true
      example: "morning"
      selector:
        select:
          options:
            - value: "morning"
              label: "Frühstück"
            - value: "lunch" 
              label: "Mittagessen"
            - value: "evening"
              label: "Abendessen"
            - value: "snack"
              label: "Leckerli"
    message:
      name: Nachricht
      description: Benutzerdefinierte Erinnerungsnachricht (optional)
      required: false
      example: "Zeit für das Frühstück!"
      selector:
        text:
          multiline: false
    dog_name:
      name: Hundename
      description: Name des spezifischen Hundes (optional, sonst alle Hunde)
      required: false
      example: "rex"
      selector:
        text:
          multiline: false

daily_reset:
  name: Täglicher Reset
  description: Setzt alle Tagesstatistiken für einen oder alle Hunde zurück
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    dog_name:
      name: Hundename
      description: Name des spezifischen Hundes (optional, sonst alle Hunde)
      required: false
      example: "rex"
      selector:
        text:
          multiline: false

send_notification:
  name: Benachrichtigung senden
  description: Sendet eine benutzerdefinierte Benachrichtigung
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    title:
      name: Titel
      description: Titel der Benachrichtigung
      required: true
      example: "Hundesystem Erinnerung"
      selector:
        text:
          multiline: false
    message:
      name: Nachricht
      description: Inhalt der Benachrichtigung
      required: true
      example: "Das ist eine Testnachricht"
      selector:
        text:
          multiline: true
    target:
      name: Ziel
      description: Spezifisches Benachrichtigungsziel (optional)
      required: false
      example: "mobile_app_smartphone"
      selector:
        text:
          multiline: false
    dog_name:
      name: Hundename
      description: Name des spezifischen Hundes (optional, sonst alle Hunde)
      required: false
      example: "rex"
      selector:
        text:
          multiline: false
    data:
      name: Zusätzliche Daten
      description: Zusätzliche Daten für die Benachrichtigung (z.B. Aktionen)
      required: false
      example: '{"actions": [{"action": "reply", "title": "Antworten"}]}'
      selector:
        object:

set_visitor_mode:
  name: Besuchsmodus setzen
  description: Aktiviert oder deaktiviert den Besuchsmodus
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    enabled:
      name: Aktiviert
      description: Besuchsmodus aktivieren oder deaktivieren
      required: true
      example: true
      selector:
        boolean:
    visitor_name:
      name: Besuchername
      description: Name des Besuchers oder Hundesitters (optional)
      required: false
      example: "Maria Müller"
      selector:
        text:
          multiline: false
    dog_name:
      name: Hundename
      description: Name des spezifischen Hundes (optional, sonst alle Hunde)
      required: false
      example: "rex"
      selector:
        text:
          multiline: false

log_activity:
  name: Aktivität protokollieren
  description: Protokolliert eine Hundeaktivität mit optionalen Details
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    activity_type:
      name: Aktivitätstyp
      description: Art der Aktivität
      required: true
      example: "walk"
      selector:
        select:
          options:
            - value: "walk"
              label: "Gassi gehen"
            - value: "outside"
              label: "Draußen"
            - value: "play"
              label: "Spielen"
            - value: "training"
              label: "Training"
            - value: "poop"
              label: "Geschäft gemacht"
            - value: "vet"
              label: "Tierarzt"
            - value: "grooming"
              label: "Pflege"
            - value: "other"
              label: "Sonstiges"
    duration:
      name: Dauer
      description: Dauer der Aktivität in Minuten (optional)
      required: false
      example: 30
      selector:
        number:
          min: 1
          max: 480
          unit_of_measurement: "min"
    notes:
      name: Notizen
      description: Zusätzliche Notizen zur Aktivität (optional)
      required: false
      example: "Schöner Spaziergang im Park, hat viel geschnüffelt"
      selector:
        text:
          multiline: true
    dog_name:
      name: Hundename
      description: Name des spezifischen Hundes (optional, sonst alle Hunde)
      required: false
      example: "rex"
      selector:
        text:
          multiline: false

add_dog:
  name: Neuen Hund hinzufügen
  description: Fügt einen neuen Hund zum System hinzu (experimentell)
  fields:
    dog_name:
      name: Hundename
      description: Name des neuen Hundes (nur Buchstaben, Zahlen, Unterstriche)
      required: true
      example: "bella"
      selector:
        text:
          multiline: false
    push_devices:
      name: Push-Geräte
      description: Liste der Benachrichtigungsgeräte (optional)
      required: false
      example: ["mobile_app_smartphone", "telegram"]
      selector:
        select:
          options: []
          multiple: true
          mode: dropdown
    door_sensor:
      name: Türsensor
      description: Sensor zur automatischen Erkennung von Türbewegungen (optional)
      required: false
      example: "binary_sensor.garden_door"
      selector:
        entity:
          filter:
            domain: binary_sensor
    create_dashboard:
      name: Dashboard erstellen
      description: Automatisch ein Dashboard für den neuen Hund erstellen
      required: false
      default: true
      selector:
        boolean:

test_notification:
  name: Test-Benachrichtigung
  description: Sendet eine Test-Benachrichtigung zur Überprüfung der Konfiguration
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    dog_name:
      name: Hundename
      description: Name des spezifischen Hundes (optional, sonst alle Hunde)
      required: false
      example: "rex"
      selector:
        text:
          multiline: false

emergency_contact:
  name: Notfallkontakt
  description: Sendet eine Notfallbenachrichtigung an alle konfigurierten Kontakte
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    emergency_type:
      name: Art des Notfalls
      description: Typ des Notfalls
      required: true
      example: "medical"
      selector:
        select:
          options:
            - value: "medical"
              label: "Medizinischer Notfall"
            - value: "lost"
              label: "Hund vermisst"
            - value: "injury"
              label: "Verletzung"
            - value: "behavioral"
              label: "Verhaltensproblem"
            - value: "other"
              label: "Sonstiger Notfall"
    message:
      name: Notfallnachricht
      description: Beschreibung des Notfalls
      required: true
      example: "Rex zeigt Anzeichen von Unwohlsein und braucht sofortige Hilfe"
      selector:
        text:
          multiline: true
    location:
      name: Standort
      description: Aktueller Standort (optional)
      required: false
      example: "Zuhause / Park Mitte / Tierarzt Dr. Schmidt"
      selector:
        text:
          multiline: false
    contact_vet:
      name: Tierarzt kontaktieren
      description: Auch den Tierarzt benachrichtigen
      required: false
      default: false
      selector:
        boolean:
    dog_name:
      name: Hundename
      description: Name des betroffenen Hundes
      required: true
      example: "rex"
      selector:
        text:
          multiline: false

health_check:
  name: Gesundheitscheck
  description: Führt eine Bewertung des Gesundheitszustands durch
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    check_type:
      name: Art der Untersuchung
      description: Typ des Gesundheitschecks
      required: false
      default: "general"
      selector:
        select:
          options:
            - value: "general"
              label: "Allgemein"
            - value: "feeding"
              label: "Fütterung"
            - value: "activity"
              label: "Aktivität"
            - value: "behavior"
              label: "Verhalten"
            - value: "symptoms"
              label: "Symptome"
    notes:
      name: Beobachtungen
      description: Spezielle Beobachtungen oder Symptome
      required: false
      example: "Hund wirkt müde und trinkt viel Wasser"
      selector:
        text:
          multiline: true
    temperature:
      name: Körpertemperatur
      description: Gemessene Körpertemperatur in °C (optional)
      required: false
      example: 38.5
      selector:
        number:
          min: 35.0
          max: 42.0
          step: 0.1
          unit_of_measurement: "°C"
    weight:
      name: Gewicht
      description: Aktuelles Gewicht in kg (optional)
      required: false
      example: 25.5
      selector:
        number:
          min: 0.1
          max: 100.0
          step: 0.1
          unit_of_measurement: "kg"
    dog_name:
      name: Hundename
      description: Name des zu untersuchenden Hundes
      required: true
      example: "rex"
      selector:
        text:
          multiline: false

schedule_reminder:
  name: Erinnerung planen
  description: Plant eine zukünftige Erinnerung für bestimmte Aktivitäten
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    reminder_type:
      name: Erinnerungstyp
      description: Art der Erinnerung
      required: true
      example: "vet_appointment"
      selector:
        select:
          options:
            - value: "feeding"
              label: "Fütterung"
            - value: "walk"
              label: "Gassi gehen"
            - value: "medication"
              label: "Medikament"
            - value: "vet_appointment"
              label: "Tierarzttermin"
            - value: "grooming"
              label: "Pflege"
            - value: "training"
              label: "Training"
            - value: "custom"
              label: "Benutzerdefiniert"
    scheduled_time:
      name: Geplante Zeit
      description: Datum und Uhrzeit für die Erinnerung
      required: true
      example: "2024-01-15 14:30:00"
      selector:
        datetime:
    message:
      name: Erinnerungsnachricht
      description: Text der Erinnerung
      required: true
      example: "Tierarzttermin um 15:00 Uhr nicht vergessen!"
      selector:
        text:
          multiline: true
    repeat:
      name: Wiederholen
      description: Erinnerung wiederholen
      required: false
      default: false
      selector:
        boolean:
    repeat_interval:
      name: Wiederholungsintervall
      description: Wie oft wiederholen (nur wenn Wiederholen aktiviert)
      required: false
      example: "daily"
      selector:
        select:
          options:
            - value: "daily"
              label: "Täglich"
            - value: "weekly"
              label: "Wöchentlich"
            - value: "monthly"
              label: "Monatlich"
    dog_name:
      name: Hundename
      description: Name des Hundes für die Erinnerung
      required: true
      example: "rex"
      selector:
        text:
          multiline: false

update_dog_info:
  name: Hundeinformationen aktualisieren
  description: Aktualisiert grundlegende Informationen über den Hund
  target:
    entity:
      domain: sensor
      integration: hundesystem
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "rex"
      selector:
        text:
          multiline: false
    breed:
      name: Rasse
      description: Rasse des Hundes (optional)
      required: false
      example: "Golden Retriever"
      selector:
        text:
          multiline: false
    age_years:
      name: Alter (Jahre)
      description: Alter in Jahren (optional)
      required: false
      example: 5
      selector:
        number:
          min: 0
          max: 30
          step: 1
          unit_of_measurement: "Jahre"
    weight:
      name: Gewicht
      description: Aktuelles Gewicht in kg (optional)
      required: false
      example: 25.5
      selector:
        number:
          min: 0.1
          max: 100.0
          step: 0.1
          unit_of_measurement: "kg"
    microchip_id:
      name: Mikrochip ID
      description: Mikrochip-Identifikationsnummer (optional)
      required: false
      example: "123456789012345"
      selector:
        text:
          multiline: false
    vet_contact:
      name: Tierarzt Kontakt
      description: Kontaktinformationen des Tierarztes (optional)
      required: false
      example: "Dr. Schmidt, Tel: 0123-456789"
      selector:
        text:
          multiline: false
    emergency_contact:
      name: Notfallkontakt
      description: Notfallkontakt (optional)
      required: false
      example: "Maria Müller, Tel: 0987-654321"
      selector:
        text:
          multiline: false