set_status:
  description: 'Setzt den Status eines Hundes (z. B. draußen, gegessen)'
  fields:
    name:
      description: 'Name des Hundes'
      example: 'Rex'
    status:
      description: 'Neuer Status'
      example: 'Gassi erledigt' 