name: Validate HACS Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compile Python files (check syntax)
        run: python -m py_compile custom_components/hundesystem/*.py

      - name: Validate manifest.json
        run: |
          python -m json.tool < custom_components/hundesystem/manifest.json > /dev/null

      - name: Run HACS Action Validator
        uses: hacs/action@main
        with:
          category: integration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
